name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Configure git for private modules
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://loongy:${PERSONAL_ACCESS_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Run vetting
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          cd $GITHUB_WORKSPACE
          go vet ./...
      - name: Run linting
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u golang.org/x/lint/golint
          go vet ./...
          golint ./...
      - name: Run tests
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          CI: true
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/mattn/goveralls
          go test --race --cover --coverprofile mpc.coverprofile ./...
